In [4]:
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd

In [5]:
df_heracleum = pd.read_csv('Heracleum mantegazzianum.csv')
df_heracleum.sample(10)

/tmp/ipykernel_2397/2201807413.py:1: DtypeWarning: Columns (0: Heracleum mantegazzianum) have mixed types. Specify dtype option on import or set low_memory=False.
  df_heracleum = pd.read_csv('Heracleum mantegazzianum.csv')

,decimalLatitude,decimalLongitude,eventDate,total_observations,speciesgroup_observations,Heracleum mantegazzianum
10616845,53.00,7.00,2021-05-04,6.0,0,0
7045006,52.30,7.00,2018-03-06,0.0,0,0
8251442,52.55,5.85,2025-03-21,3.0,1,0
12530875,53.50,6.30,2013-09-01,0.0,0,0
1119141,51.35,5.30,2018-01-16,0.0,0,0
11191783,53.15,5.60,2011-06-08,0.0,0,0
10249399,52.95,6.00,2023-04-30,0.0,0,0
8191649,52.55,5.00,2021-07-07,31.0,0,0
10237077,52.95,5.90,2021-08-04,2.0,1,0
3848983,51.80,5.80,2019-12-11,10.0,0,0

In [6]:
df_heracleum.info(verbose=True)
df_heracleum.describe()

<class 'pandas.DataFrame'>
RangeIndex: 12558786 entries, 0 to 12558785
Data columns (total 6 columns):
 #   Column                     Dtype
---  ------                     -----
 0   decimalLatitude            float64
 1   decimalLongitude           float64
 2   eventDate                  str
 3   total_observations         float64
 4   speciesgroup_observations  int64
 5   Heracleum mantegazzianum   object
dtypes: float64(3), int64(1), object(1), str(1)
memory usage: 574.9+ MB

,decimalLatitude,decimalLongitude,total_observations,speciesgroup_observations
count,1.255879e+07,1.255879e+07,1.255878e+07,1.255879e+07
mean,5.222995e+01,5.532896e+00,8.132578e+00,1.250141e+00
std,6.647267e-01,8.779710e-01,5.593690e+01,8.645628e+00
min,3.500000e+00,3.350000e+00,0.000000e+00,0.000000e+00
25%,5.170000e+01,4.900000e+00,0.000000e+00,0.000000e+00
50%,5.220000e+01,5.650000e+00,1.000000e+00,0.000000e+00
75%,5.280000e+01,6.200000e+00,6.000000e+00,0.000000e+00
max,5.350000e+01,5.340000e+01,1.000400e+05,5.227000e+03

In [7]:
df_heracleum.duplicated()

0           False
1           False
2           False
3           False
4           False
            ...
12558781    False
12558782    False
12558783    False
12558784    False
12558785    False
Length: 12558786, dtype: bool